name: Test and deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'lambda_fetch/**'
      - 'lambda_validate/**'
      - '.github/workflows/test_and_deploy.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/deploy_lambdas.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'lambda_fetch/**'
      - 'lambda_validate/**'
      - '.github/workflows/test_and_deploy.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/deploy_lambdas.yml'

concurrency:
  group: ${{ github.ref }}   
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  test:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    uses: ./.github/workflows/test.yml

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: test
    uses: ./.github/workflows/deploy_lambdas.yml